name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Publish
    runs-on: ubuntu

    env:
      SERVER_URL: https://code.snipcola.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          github-server-url: ${{ env.SERVER_URL }}

      - name: Publish
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.npm_auth }}
