name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Publish
    runs-on: ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Publish
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          token: ${{ secrets.NPM_AUTH }}
